version: "3.7"

services:
  app:
    restart: always
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: react-app
    command: ["npm", "start"]
    volumes:
      - .:/app
      - .:/app/node_modules
    ports:
      - 3001:3000
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true